# Generated by Django 3.2.5 on 2021-10-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('similar_art', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
